[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[client]
showErrorDetails = true
toolbarMode = "minimal"