[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"
